#!/bin/bash
#
MYSQL_AUTHORIZATION="-u ${TRAVISCI_MYSQL_USERNAME}"
#
if [ -n "${TRAVISCI_MYSQL_PASSWORD}" ]; then
	MYSQL_AUTHORIZATION="${MYSQL_AUTHORIZATION} -p${TRAVISCI_MYSQL_PASSWORD}";
fi;
#
mysql ${MYSQL_AUTHORIZATION} << __END_SQL__ 2>&1
create database ${TRAVISCI_MYSQL_DBNAME};

use ${TRAVISCI_MYSQL_DBNAME};

CREATE TABLE messy_table (
    mt_id      INT(11) NOT NULL,
    mt_text    TEXT NOT NULL,
    mt_null    INT(11) DEFAULT NULL,
    no_prefix  INT(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE messy_table ADD PRIMARY KEY (mt_id);
ALTER TABLE messy_table MODIFY mt_id int(11) NOT NULL AUTO_INCREMENT;

CREATE TABLE tab_users (
    usr_id    INT(11) NOT NULL,
    username  VARCHAR(62) NOT NULL,
    password  VARCHAR(256) NOT NULL,
    age       INT(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE tab_users ADD PRIMARY KEY (usr_id);
ALTER TABLE tab_users MODIFY usr_id int(11) NOT NULL AUTO_INCREMENT;
__END_SQL__
